image:
  file: .gitpod/Dockerfile

tasks:
  - name: commerce-api
    before: |
      cd ../commerce-api
    init: |
      sudo setfacl -dR -m u:$(whoami):rwX -m u:1000:rwX .
      sudo setfacl -R -m u:$(whoami):rwX -m u:1000:rwX  .
      cp .gitpod/docker-compose.override.yml .
      make database
      make up
      make composer install
      make drush deploy
      make stop
      sudo setfacl -dR -m u:$(whoami):rwX -m u:1000:rwX .
      sudo setfacl -R -m u:$(whoami):rwX -m u:1000:rwX  .
    command: |
      sudo setfacl -dR -m u:$(whoami):rwX -m u:1000:rwX .
      sudo setfacl -R -m u:$(whoami):rwX -m u:1000:rwX  .
      make up
      make drush cr
      make drush uli
      sudo setfacl -dR -m u:$(whoami):rwX -m u:1000:rwX .
      sudo setfacl -R -m u:$(whoami):rwX -m u:1000:rwX  .
  - name: next-drupal
    init: |
      npm install
    command: |
      envsubst < .env.example > .env.local
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser
  - port: 80
    onOpen: open-browser

additionalRepositories:
  - url: https://github.com/isobar-playground/commerce-api
    checkoutLocation: commerce-api

workspaceLocation: next-drupal/main.code-workspace

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
